import type { WhyNumberOne as WhyNumberOneData } from "../../utils/whyNumberOne";

export default function WhyNumberOne({
  data,
  llmInfo,
}: {
  data: WhyNumberOneData;
  llmInfo?: string | null;
}) {
  return (
    <div className="why-number-one">
      <div className="why-number-one-col why-number-one-col--strengths">
        <div className="why-number-one-head">
          <span className="why-number-one-icon why-number-one-icon--good">
            ✓
          </span>
          Strengths
        </div>
        <ul className="why-number-one-list">
          {data.strengths.map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ul>
      </div>

      <div className="why-number-one-col why-number-one-col--watch">
        <div className="why-number-one-head">
          <span className="why-number-one-icon why-number-one-icon--warn">
            !
          </span>
          Watch-outs
        </div>
        {data.watchOuts.length > 0 ? (
          <ul className="why-number-one-list">
            {data.watchOuts.map((w, i) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
        ) : (
          <p className="why-number-one-empty">
            No material watch-outs identified.
          </p>
        )}
      </div>

      <div className="why-number-one-col why-number-one-col--conclusion why-number-one-conclusion">
        <div className="why-number-one-head why-number-one-head--plain">
          AI Conclusion
        </div>
        <p className="why-number-one-conclusion-text">{data.conclusion}</p>
        {llmInfo && (
          <p className="why-number-one-attribution">Generated by {llmInfo}</p>
        )}
      </div>
    </div>
  );
}
