import type { WhyNumberOne as WhyNumberOneData } from "../../utils/whyNumberOne";

/**
 * Redesign spec item 9 ("Add a 'Why #1?' Visual"): replaces a single long
 * AI-generated paragraph with clearly labeled sections — a green Strengths
 * box, an amber Watch-outs box, and a full-width AI conclusion box — so the
 * reasoning behind the top recommendation can be scanned in a few seconds
 * instead of read as prose.
 */
export default function WhyNumberOne({
  data,
  llmInfo,
}: {
  data: WhyNumberOneData;
  /** Shown as a small attribution line under the AI conclusion text. */
  llmInfo?: string | null;
}) {
  return (
    <div className="why-number-one">
      <div className="why-number-one-col why-number-one-col--strengths">
        <div className="why-number-one-head">
          <span className="why-number-one-icon why-number-one-icon--good">✓</span>
          Strengths
        </div>
        <ul className="why-number-one-list">
          {data.strengths.map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ul>
      </div>

      <div className="why-number-one-col why-number-one-col--watch">
        <div className="why-number-one-head">
          <span className="why-number-one-icon why-number-one-icon--warn">!</span>
          Watch-outs
        </div>
        {data.watchOuts.length > 0 ? (
          <ul className="why-number-one-list">
            {data.watchOuts.map((w, i) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
        ) : (
          <p className="why-number-one-empty">No material watch-outs identified.</p>
        )}
      </div>

      <div className="why-number-one-col why-number-one-col--conclusion why-number-one-conclusion">
        <div className="why-number-one-head why-number-one-head--plain">AI Conclusion</div>
        <p className="why-number-one-conclusion-text">{data.conclusion}</p>
        {llmInfo && <p className="why-number-one-attribution">Generated by {llmInfo}</p>}
      </div>
    </div>
  );
}
